### ISSUE TITLE
Get CircleCI working

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-scripts#20]
Hey @danielballan, and chance you could give this a once-over and let me know if anything jumps out?

I seem to have it working, but the repo isn't kicking off each push. It's really weird. I get each payload to resend, and github says it goes out, but circleci says nothing, not even a complaint.

Any thoughts?

**Comment by danielballan** [comment]
Sorry, not sure why I didn't see this go by.

I have fiddled a little bit but with no success yet. I'll keep a tab open and revisit this....

**Comment by danielballan** [comment]
@Mr0grog and I are both stumped. Contact Circle-CI support?

**Comment by dcwalk** [comment]
🙏 thank you both for taking a look. @patcon you able to handle or want me to reach out?

**Comment by patcon** [comment]
Thanks all! Step one seems done (Great commit message, rob!)

I'll close this out when I confirm that it's running cron, here:
https://github.com/edgi-govdata-archiving/edgi-scripts#usage-via-circleci

**Comment by patcon** [comment]
Related: https://github.com/edgi-govdata-archiving/edgi-scripts/pull/25#issuecomment-366094721

**Comment by patcon** [comment]
Confirmed working for nightly workflow! https://circleci.com/gh/edgi-govdata-archiving/edgi-scripts

Thanks friend-o's! :tada:
