### ISSUE TITLE
Zoomus library now defaults to V2 API

### ISSUE THREAD

**Issue by prschmid** [edgi-govdata-archiving/edgi-scripts#49]
Hi! I'm the maintainer of the `zoomus` libarary and  wanted to let you know that we have updated the zoomus library that you depend on to default to using V2 Zoom API. If the code you have written depends on the V1 API, please make sure to update your client configuration to specify to use the V1 API. This can be done by simply adding in a version flag when you instantiate the client.

```python
client = ZoomClient('API_KEY', 'API_SECRET', version=1)
```

Note: Although Zoom has yet to officially drop support for the V1 API, I suggest you update your code to work with their V2 API to ensure that there are no interruptions.

**Comment by lightandluck** [comment]
Thanks @prschmid for pointing this out!
