### ISSUE TITLE
Can't update default branch to main

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/edgi-scripts#65]
@Mr0grog @Frijol 
Every time I try to change the default branch, when I refresh, it just changes back to `master`. Can y'all try to change it and see if you have the same problem?

**Comment by Mr0grog** [comment]
Not working for me, either. Maybe submit a support ticket: https://support.github.com/contact

**Comment by Mr0grog** [comment]
(Tried both the UI and API, no dice on either.)

**Comment by lightandluck** [comment]
Thanks for checking! I submitted a ticket.

**Comment by lightandluck** [comment]
No new updates, other than Github saying that this issue is affecting other users

**Comment by lightandluck** [comment]
Fixed this by deleting `.github/settings.yml`. Also, uninstalled the Settings app
